
openapi: 3.0.0
info:
  title: Duoduo Plugin API
  description: API pour accéder aux services de Duoduo (CRO, UX, UI, Shopify, Webflow).
  version: '1.0'
servers:
  - url: https://YOUR_RENDER_URL
paths:
  /services:
    get:
      summary: Liste des services proposés
      operationId: getServices
      responses:
        '200':
          description: Services disponibles et infos de contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      type: string
                  contact:
                    type: object
                    properties:
                      website:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
